In [1]:
import numpy as np

In [46]:
data = [
    [0,1,2],
    [3,4,5],
    [6,7,8],
    [9,10,11]
]
rows = 3
cols = 3
depth = 2
r = 2
c = 1
d = 1
print(d + (c + r * cols) * depth)
print("###")
data_np = np.array(data)
print("data_np shape: " + str(data_np.shape))
data_np_reshaped = data_np.reshape((4,3,1))
print("data_np_reshaped: " + str(data_np_reshaped))
data_flat = data_np.reshape(-1)
print(data_flat)
data_flat = np.concatenate((data_flat, [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]))
print(data_flat)
data_3d = data_flat.reshape((4,3,2))
print("data_3d:\n:" + str(data_3d))
print("---")
print(data_3d[0])
print(data_3d[0][0])

15
###
data_np shape: (4, 3)
data_np_reshaped: [[[ 0]
  [ 1]
  [ 2]]

 [[ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
data_3d:
:[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
---
[[0 1]
 [2 3]
 [4 5]]
[0 1]
